---
- name: Verify login to Docker
  hosts: all
  become: yes
  tasks:
    - name: Verify Docker login
      block:
        - name: Check for login status
          shell: 'docker info | grep Username'
          register: login_status
          ignore_errors: yes

        - name: Docker login Required
          debug:
            msg: "Login to Docker Hub present"
          when: login_status.rc == 0

    - name: Docker Login process
      block:
        - name: Verify Docker login status
          debug:
            msg: "Docker Hub Login Required"

        - name: Enter Docker Hub username
          pause:
            prompt: Enter Docker username
            echo: true
          register: d_username

        - set_fact:
            docker_username: "{{ d_username.user_input }}"

        - name: Enter Docker Hub password
          pause:
            prompt: Enter Docker password
            echo: false
          register: d_password

        - set_fact:
            docker_password: "{{ d_password.user_input }}"

        - name: Logging into Docker Hub
          community.docker.docker_login:
            username: "{{ docker_username }}"
            password: "{{ docker_password }}"
          with_items: groups['lab']

        - name: Display Docker login success
          debug:
            msg: "Logged into Docker Hub successfully"
      when: login_status.rc == 1




 
