---
- name: Docker login
  hosts: servera.example.com
  become: yes
  vars_prompt:
    - name: docker_hub_username
      prompt: Enter you Docker Hub username
      private: no
    - name: docker_hub_password
      prompt: Enter you Docker Hub password
  tasks:
    - name: Login to Docker
      community.docker.docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password}}"

